image:
  tag: env-test-ns-cleanup-verify-73d1b-bb318f3
env:
  dynamodbTable: noteapp-notes-nonprod
  s3BucketName: noteapp-images-nonprod-686062433938-eu-north-1
serviceAccount:
  roleArn: arn:aws:iam::686062433938:role/noteapp-app-nonprod
ephemeral:
  enabled: true
createdAt: "2026-08-21T13:55:24Z"
ttlHours: 24
