image:
  tag: env-feature-yarin-test-2bb86-b5ea05e
env:
  scriptName: /env/feature-yarin-test-2bb86
  dynamodbTable: noteapp-notes-nonprod
  s3BucketName: noteapp-images-nonprod-686062433938-eu-north-1
serviceAccount:
  roleArn: arn:aws:iam::686062433938:role/noteapp-app-nonprod
ingress:
  pathPrefix: /env/feature-yarin-test-2bb86
  groupOrder: "100"
createdAt: "2026-08-21T13:19:56Z"
ttlHours: 24
