apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noteapp-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: main
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: "88.5.3"
      helm:
        valueFiles:
          - $values/helm/monitoring/values.yaml
    - repoURL: https://github.com/yarinlaniado/noteapp.git
      targetRevision: main
      path: helm/monitoring
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
