# Here we have all we need to deploy the app alongside mongodb and a filebeat that sends the logs to elasticsearch
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001/" # replace with the actual path on the host

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0002/" # replace with the actual path on the host

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: yarinlaniado/mongo:1.0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "note"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "note"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
          
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-app
  template:
    metadata:
      labels:
        app: note-app
    spec:
      containers:
      - name: note-app
        image: yarinlaniado/noteapp:2.4.0
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: logs
          mountPath: /Noteapp/app/logs

      - name: filebeat
        image: elastic/filebeat:8.11.1
        args: ["-c", "/etc/filebeat/filebeat.yml", "-e"]
        volumeMounts:
        - name: filebeat-config
          mountPath: /etc/filebeat
        - name: logs
          mountPath: /logs
        - name: filebeat-ca
          mountPath: /usr/share/filebeat/ca.crt 
          subPath: ca.crt

      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: logs
      - name: filebeat-ca
        secret:
          secretName: quickstart-es-http-certs-public #make sure that it is existing!
      - name: filebeat-config
        configMap:
          name: filebeat-config

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: note-app
spec:
  selector:
    app: note-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000

